api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

shop = [
    path('card-carousel/', views.ShopCardCarouselView.as_view(), name='shop-card-carousel'),
    path('cart-add/', views.CartAddView.as_view(), name='cart-add'),
    path('cart-delete/', views.CartDeleteView.as_view(), name='cart-delete'),
    path('cart-delivery/', views.CartDeliveryView.as_view(), name='cart-delivery')
]

urlpatterns = [
    path('shop/', include(shop)),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('user/', views.order_user_view, name='user'),
    path('details/', views.order_details_view, name='details'),
    path('cart/', views.order_cart_view, name='cart'),
    path('payment/', views.order_payment_view, name='payment'),
    path('payment-check/', views.order_payment_check_view, name='payment-check'),
    path('done/', views.order_done_view, name='done'),
]

templates/cart/cart-product.html
<div class="row">

{% if is_control_included %}
<div class="col-4 col-lg-2 order-3 order-lg-6 d-flex align-items-center">
    <a href="{{ origin.get_absolute_url }}?color={{ product.color }}">
        <div class="css-icon css-icon-24px css-icon-edit css-icon-hover"></div>
    </a>
    <div class="ml-3 css-icon css-icon-hover css-icon-24px css-icon-trash css-icon-hover js-cart-product-trash" data-product-slug="{{ product.slug }}"></div>
</div>
{% endif %}

<div class="col-4 col-lg-2 d-flex align-items-center justify-content-lg-center order-1 order-lg-1">
    <div class="css-width-80px">
        <img class="d-block w-100" src="{{ product.small_photo.url }}" alt="Product {{ product.slug }}">
    </div>
</div>

<div class="col-4 col-lg-2 d-flex flex-column justify-content-center order-2 order-lg-2">
    <a href="{{ origin.get_absolute_url }}?color={{ product.color }}">
        <div class="h5 my-0 text-color-2">
            <u>{{ origin.name }}</u>
        </div>
    </a>
    <div class="h6 my-0 mt-1 font-weight-normal">
        {{ product.get_color_display }}
    </div>
</div>

<div class="col-4 col-lg-2 py-3 py-lg-0 d-flex flex-column justify-content-center order-4 order-lg-3">
    <div class="d-lg-none h6 my-0">
        Цена
    </div>
    <div class="h6 my-0 mt-2 mt-lg-0 font-weight-normal text-nowrap">
        {{ origin.price }} тг.
    </div>
</div>

<div class="col-4 col-lg-2 py-3 py-lg-0 d-flex flex-column justify-content-center order-5 order-lg-4">
    <div class="d-lg-none h6 my-0">
        Количество
    </div>
    <div class="h6 my-0 mt-2 mt-lg-0 font-weight-normal">
        {{ quantity }} шт.
    </div>
</div>

<div class="col-4 col-lg-2 py-3 py-lg-0 d-flex flex-column justify-content-center order-6 order-lg-5">
    <div class="d-lg-none h6 my-0">
        Всего
    </div>
    <div class="h6 my-0 mt-2 mt-lg-0 font-weight-normal">
        {{ total }} тг.
    </div>
</div>

</div>

templates/cart/cart-summary.html
{% load static %}
{% load math %}

<div class="d-flex flex-column bg-color-gray-300 p-3">
    <div class="h4 my-0">
        Оформить заказ
    </div>
    <div class="d-block">
        <hr class="my-3">
    </div>
    <div class="custom-control custom-switch">
        <input type="checkbox" class="ml-auto custom-control-input js-cart-is-fast-delivery-input" id="id_cart_is_fast_delivery_input"
               {% if is_fast_delivery %}checked="checked"{% endif %}
               data-next-state="{% if is_fast_delivery %}false{% else %}true{% endif %}">
        <label class="custom-control-label" for="id_cart_is_fast_delivery_input">
            Быстрая доставка <span class="text-nowrap">в течение</span> <span class="text-nowrap">1-2 дней</span>
        </label>
    </div>
    <div class="d-block">
        <hr class="my-3">
    </div>
    <div class="d-flex justify-content-between">
        <div class="h6 my-0 font-weight-normal">
            Всего:
        </div>
        <div class="h6 my-0">
            {{ total }} тг.
        </div>
    </div>
    <div class="d-flex justify-content-between mt-3">
        <div class="h6 my-0 font-weight-normal">
            Доставка:
        </div>
        <div class="h6 my-0">
            <span class="js-cart-delivery-price">{% if is_fast_delivery %}5550{% else %}1750{% endif %}</span> тг.
        </div>
    </div>
    <div class="d-block">
        <hr class="my-3">
    </div>
    <div class="d-flex justify-content-between">
        <div class="h6 my-0">
            Итого:
        </div>
        <div class="h6 my-0">
            <span class="js-cart-summary-total" data-total="{{ total }}">{% if is_fast_delivery %}{{ total|add:"5550" }}{% else %}{{ total|add:"1750" }}{% endif %}</span> тг.
        </div>
    </div>
    <div class="mt-3">
        <a href="{% url 'orders:user' %}" class="btn btn-block btn-color-2">
            Оформить заказ
        </a>
    </div>
    <div class="d-flex justify-content-center mt-2">
        <div class="css-icon css-icon-34px">
            <img class="d-block w-100" src="{% static 'img/cash_in_hand_48px.png' %}" alt="Visa">
        </div>
        <div class="css-icon css-icon-34px ml-2">
            <img class="d-block w-100" src="{% static 'img/visa_48px.png' %}" alt="Visa">
        </div>
        <div class="css-icon css-icon-34px ml-2">
            <img class="d-block w-100" src="{% static 'img/mastercard_logo_48px.png' %}" alt="MasterCard">
        </div>
    </div>
    <div class="px-3 px-lg-0 mt-2">
        <div class="text-center"><small>
            Вы можете оплатить наличными или банковской картой.
            Изготовление некоторых товаров требует <span class="text-nowrap">2-3 дней</span>.
            Обычная доставка осуществляется в течение <span class="text-nowrap">3-8 дней</span>, а быстрая <span class="text-nowrap">доставка - в</span> течение <span class="text-nowrap">1-2 дней</span>.
        </small></div>
    </div>
</div>

templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% load math %}

{% block pretitle %}
    Корзина |
{% endblock %}

{% block content %}
    <div class="container-fluid container-fluid-max-width">
        <div class="row py-1">
        </div>
        <div class="row py-3 bg-white">
            <div class="col-12 px-3 px-lg-5">
                <div class="h2 my-0 font-weight-normal">
                    Корзина
                </div>
            </div>
            {% if results %}
            <div class="col-12 col-lg-9">
                <div class="row">
                    <div class="d-none d-lg-block col-2 offset-4">
                        <div class="h6 my-0">
                            Цена
                        </div>
                    </div>
                    <div class="d-none d-lg-block col-2">
                        <div class="h6 my-0">
                            Количество
                        </div>
                    </div>
                    <div class="d-none d-lg-block col-2">
                        <div class="h6 my-0">
                            Всего
                        </div>
                    </div>
                    <div class="col-12">
                        <hr class="my-3">
                    </div>
                    {% with is_control_included=True %}
                    {% for product, origin, quantity, total in results %}
                    <div class="col-12 col-sm-9 col-lg-12">
                        {% include 'cart/cart-product.html' %}
                    </div>
                    <div class="col-12">
                        <hr class="my-3">
                    </div>
                    {% endfor %}
                    {% endwith %}
                    <div class="col-4 col-sm-3 col-lg-2 offset-4 offset-sm-3 offset-lg-6">
                        <div class="h5 my-0">
                            Всего:
                        </div>
                    </div>
                    <div class="col-4 col-lg-2">
                        <div class="h5 my-0">
                            {{ total }} тг.
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-12 col-lg-3 p-3">
                {% include 'cart/cart-summary.html' %}
            </div>

            {% else %}
            <div class="col-12">
                <div class="d-flex flex-column align-items-center">
                    <div class="d-block">
                        <img class="d-block css-width-100px" src="{% static 'img/shopping_cart_125px.png' %}" alt="Корзина">
                    </div>
                    <div class="h5 my-1 font-weight-normal text-center">
                        Ваша корзина сейчас пуста.
                    </div>
                    <div class="h5 my-1 font-weight-normal text-center">
                        Чтобы перейти в магазин, нажмите <a href="{% url 'shop' %}" class="text-color-2">сюда</a>.
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>

    <form action="{% url 'api:cart-delete' %}" method="post" class="d-none js-cart-delete-form">
        {% csrf_token %}
        {{ cart_delete_form.product_slug }}
    </form>
{% endblock %}

{% block script %}
    <script>
        var api_cart_delivery = '{% url 'api:cart-delivery' %}';
    </script>
{% endblock %}