accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('activation/<user_email_b64>/<token>/', views.activate_view, name='activate'),
    path('login/', views.login_view, name='login'),
    path('password/reset/', views.password_reset_view, name='password-reset'),
    path('password/set/<user_email_b64>/<token>/', views.password_set_view, name='password-set'),
    path('password/change/', views.password_change_view, name='password-change'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('home')), name='logout'),
]

api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

shop = [
    path('card-carousel/', views.ShopCardCarouselView.as_view(), name='shop-card-carousel'),
    path('cart-add/', views.CartAddView.as_view(), name='cart-add'),
    path('cart-delete/', views.CartDeleteView.as_view(), name='cart-delete'),
    path('cart-delivery/', views.CartDeliveryView.as_view(), name='cart-delivery')
]

urlpatterns = [
    path('shop/', include(shop)),
]

cabinet/urls.py
from django.urls import path

from . import views


app_name = 'profile'

urlpatterns = [
    path('orders/', views.profile_orders_view, name='orders'),
    path('orders/<slug:order_slug>/', views.profile_order_view, name='order'),
    path('chats/', views.profile_chats_view, name='chats'),
    path('chats/<slug:chat_slug>/', views.profile_chat_view, name='chat'),
    path('settings/', views.profile_settings_view, name='settings'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('user/', views.order_user_view, name='user'),
    path('details/', views.order_details_view, name='details'),
    path('cart/', views.order_cart_view, name='cart'),
    path('payment/', views.order_payment_view, name='payment'),
    path('payment-check/', views.order_payment_check_view, name='payment-check'),
    path('done/', views.order_done_view, name='done'),
]

support/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'support'

urlpatterns = [
    path('', views.support_view, name='support'),
    path('<section_name>/<question_index>/', views.question_view, name='question'),
    path('chat/', views.chat_view, name='chat'),
    path('terms-of-service/',
         TemplateView.as_view(template_name='support/terms-of-service.html'),
         name='terms-of-service'),
]

cabinet/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone
from django.utils.translation import ugettext as _

from accounts.models import User
from shop.models import Product
from pufiki190630.utilities import generate_slug_and_save, args_to_str


DEFAULT_SLUG_LENGTH = 6


class Address(models.Model):
    PHONE_ERROR_MESSAGE = 'Пожалуйста, введите номер телефона в формате 87001112233 или +77001112233'
    PHONE_REGEX_VALIDATOR = RegexValidator(
        regex=r'^(8|(\+7))\d{10}$',
        message=PHONE_ERROR_MESSAGE,
        code='invalid_phone_number'
    )

    city = models.CharField(max_length=32, default='', blank=True)
    street = models.CharField(max_length=32, default='', blank=True)
    house = models.CharField(max_length=16, default='', blank=True)
    flat = models.CharField(max_length=16, default='', blank=True)
    phone = models.CharField(max_length=12, validators=[PHONE_REGEX_VALIDATOR])

    def __str__(self):
        return args_to_str(self.city, self.phone)


class Order(models.Model):
    PAYMENT_METHOD_CHOICES = (
        (1, _('Cash')),
        (2, _('Card')),
    )

    slug = models.CharField(max_length=DEFAULT_SLUG_LENGTH, unique=True, editable=False)  # handled by save method
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, default=None)
    name = models.CharField(max_length=64, default='')

    # Details
    is_fast_delivery = models.BooleanField(default=False)
    comment = models.TextField(max_length=128, blank=True, default='')
    payment_method = models.PositiveSmallIntegerField(choices=PAYMENT_METHOD_CHOICES, default=1)
    address = models.ForeignKey(Address, on_delete=models.SET_DEFAULT, null=True, default=None)

    products = models.ManyToManyField(Product, through='OrderProduct')
    total_to_pay = models.PositiveIntegerField(default=0)

    bank_id = models.CharField(max_length=36, default='', blank=True)

    date_created = models.DateTimeField(default=timezone.now)
    is_valid = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        generate_slug_and_save(self, Order, *args,
                               slug_length=DEFAULT_SLUG_LENGTH, is_slug_alphanumeric=False, **kwargs)

    def __str__(self):
        return self.slug


class OrderProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    current_price = models.PositiveIntegerField()
    quantity = models.PositiveSmallIntegerField()

    def __str__(self):
        return args_to_str(str(self.order), str(self.product.origin.name), self.product.get_color_display())


class OrderStatus(models.Model):
    STATUS_CHOICES = (
        (1, _('Packaged')),
        (2, _('Shipped')),
        (3, _('Delivered')),
        (4, _('Exchanged')),
        (5, _('Returned')),
        (6, _('Canceled')),
    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=1)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return args_to_str(str(self.order), self.get_status_display())

support/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from accounts.models import User
from pufiki190630.utilities import generate_slug_and_save, DEFAULT_SLUG_LENGTH


class Chat(models.Model):
    STATUS_CHOICES = (
        (1, _('Open')),
        (2, _('Closed')),
    )

    slug = models.CharField(max_length=DEFAULT_SLUG_LENGTH, unique=True, editable=False)  # handled by save method
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        generate_slug_and_save(self, Chat, *args, **kwargs)


class Message(models.Model):
    BODY_PRINT_LIMIT = 30

    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    is_from_user = models.BooleanField(default=True)
    body = models.CharField(max_length=512)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return (self.body[:Message.BODY_PRINT_LIMIT] + '...') \
            if len(self.body) > Message.BODY_PRINT_LIMIT \
            else self.body

cabinet/forms.py
from django.contrib.auth.forms import UserChangeForm as BaseUserChangeForm
from django import forms

from accounts.models import User


class UserChangeForm(BaseUserChangeForm):
    class Meta(BaseUserChangeForm.Meta):
        model = User
        fields = ['name']
        widgets = {
            'name': forms.TextInput(),
        }

orders/forms.py
from django import forms
from django.utils.translation import ugettext as _

from .models import Order, Address


class NameForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={
                'autofocus': True,
            }),
        }


class AddressForm(forms.ModelForm):
    CITIES = [
        _('Almaty'), _('Nur-Sultan'), _('Aktau'), _('Aktobe'), _('Atyrau'),
        _('Zhezkazgan'), _('Karaganda'), _('Kokshetau'), _('Kostanay'), _('Kyzylorda'),
        _('Taldykorgan'), _('Taraz'), _('Temirtau'), _('Uralsk'), _('Ust-Kamenogorsk'),
        _('Pavlodar'), _('Petropavlovsk'), _('Semey'), _('Shymkent'),
    ]
    CITY_DATALIST = {
        'id': 'city-choices',
        'options': CITIES,
    }

    class Meta:
        model = Address
        fields = ['city', 'street', 'house', 'flat', 'phone']
        widgets = {
            'city': forms.TextInput(attrs={
                'list': 'city-choices',
                'required': False,
            }),
            'street': forms.TextInput(attrs={
                'required': False,
            }),
            'house': forms.TextInput(attrs={
                'required': False,
            }),
            'flat': forms.TextInput(attrs={
                'required': False,
            }),
            'phone': forms.TextInput(attrs={
                'type': 'tel',
            }),
        }


class OrderDetailsForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            # 'phone',
            # 'address',
            'comment',
            'payment_method'
        ]
        widgets = {
            # 'phone': forms.TextInput(attrs={
            #     'type': 'tel',
            #     'placeholder': 'Например: 87001112233 или +77001112233',
            #     'autofocus': True,
            # }),
            # 'address': forms.Textarea(attrs={
            #     'rows': '3',
            #     'placeholder': 'Например: г. Алматы, ул. Толе би, д. 123, кв. 4',
            # }),
            'comment': forms.Textarea(attrs={
                'rows': '3',
                # 'placeholder': '(необязательно)',
            }),
            'payment_method': forms.RadioSelect(attrs={
                'class': 'custom-control-input js-payment-method-input',
            }),
        }

cabinet/views.py
from django.shortcuts import render, redirect
from django.db.models import Prefetch
from django.db import IntegrityError

from orders.models import OrderStatus
from support.models import Message
from .forms import UserChangeForm


SECTIONS = [
    ('orders', 'Мои заказы', 'profile:orders'),
    ('chats', 'Мои сообщения', 'profile:chats'),
    ('settings', 'Мои настройки', 'profile:settings'),
]


def profile_orders_view(request):
    user = request.user

    if user.is_anonymous:
        return redirect('accounts:login')

    orders = user.order_set.all() \
        .filter(is_valid=True) \
        .order_by('-id') \
        .prefetch_related(Prefetch('orderstatus_set', OrderStatus.objects.order_by('date')))

    context = dict()
    context['sections'] = SECTIONS
    context['section_name'] = 'orders'
    context['orders'] = orders

    return render(request, 'cabinet/orders.html', context=context)


def profile_order_view(request, **kwargs):
    user = request.user

    if user.is_anonymous:
        return redirect('accounts:login')

    order_slug = kwargs['order_slug']

    order = user.order_set.all() \
        .filter(slug=order_slug, is_valid=True) \
        .prefetch_related(Prefetch('orderstatus_set', OrderStatus.objects.order_by('date'))) \
        .prefetch_related('orderproduct_set') \
        .prefetch_related('orderproduct_set__product') \
        .prefetch_related('orderproduct_set__product__origin') \
        .prefetch_related('orderproduct_set__product__origin__name') \
        .prefetch_related('orderstatus_set') \
        .select_related('user') \
        .first()

    if not order:
        return redirect('profile:orders')

    context = dict()
    context['sections'] = SECTIONS
    context['order'] = order

    return render(request, 'cabinet/order.html', context=context)


def profile_chats_view(request):
    user = request.user

    if user.is_anonymous:
        return redirect('accounts:login')

    chats = user.chat_set.all() \
        .order_by('-id') \
        .prefetch_related(Prefetch('message_set', Message.objects.order_by('date')))

    context = dict()
    context['sections'] = SECTIONS
    context['section_name'] = 'chats'
    context['chats'] = chats

    return render(request, 'cabinet/chats.html', context=context)


def profile_chat_view(request, **kwargs):
    user = request.user

    if user.is_anonymous:
        return redirect('accounts:login')

    chat_slug = kwargs['chat_slug']

    chat = user.chat_set.all() \
        .filter(slug=chat_slug) \
        .prefetch_related(Prefetch('message_set', Message.objects.order_by('date'))) \
        .first()

    if not chat:
        return redirect('profile:chats')

    context = dict()
    context['sections'] = SECTIONS
    context['chat'] = chat

    return render(request, 'cabinet/chat.html', context=context)


def profile_settings_view(request):
    user = request.user

    if user.is_anonymous:
        return redirect('accounts:login')

    if request.method == 'POST':
        user_change_form = UserChangeForm(request.POST, instance=user)

        if user_change_form.is_valid():
            try:
                user_change_form.save()
            except IntegrityError:
                pass
    else:
        user_change_form = UserChangeForm(instance=user)

    context = dict()
    context['sections'] = SECTIONS
    context['section_name'] = 'settings'
    context['user_change_form'] = user_change_form

    return render(request, 'cabinet/settings.html', context=context)

templates/cabinet/base.html
{% extends 'base.html' %}

{% block title %}
    | Мой аккаунт
    {% block subtitle %}
    {% endblock %}
{% endblock %}

{% block content %}
    <div class="container-fluid container-fluid-max-width">
        <div class="row bg-light">
            <div class="col-12 py-1"></div>
        </div>
        <div class="row bg-white">
            <div class="col-12 mt-3 px-sm-4 px-lg-5">
                <div class="h2 font-weight-normal">
                    Мой аккаунт
                </div>
                <div>
                    <hr>
                </div>
            </div>
            <div class="col-12 col-lg-3 px-sm-4 pl-lg-5 pr-lg-3">
                <ul class="list-group">
                    {% for name, title, link in sections %}
                        <a href="{% url link %}"
                           class="list-group-item list-group-item-action {% if name == section_name %}active{% endif %}">
                            {{ title }}
                        </a>
                    {% endfor %}
                        <a href="{% url 'accounts:logout' %}"
                           class="list-group-item list-group-item-action">
                            Выйти
                        </a>
                </ul>
            </div>
            <div class="col-12 col-lg-9 px-sm-4 pl-lg-3 pr-lg-5">
                <hr class="d-lg-none">
                {% block subcontent %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/cabinet/chat.html
{% extends 'cabinet/base.html' %}
{% load static %}

{% block subtitle %}
    | Мои сообщения | {{ chat.title }}
{% endblock %}

{% block subcontent %}
    <div class="h5 font-weight-normal">
        {{ chat.title }}
    </div>
    <div class="mt-3 font-weight-normal">
        Статус: <span class="font-weight-bold">{{ chat.get_status_display|lower }}</span>
    </div>
    <div class="row px-3 mb-3">
    {% for message in chat.message_set.all %}
        <div class="col-10 border rounded p-3 mt-3 {% if message.is_from_user %}border-color-2 offset-2{% else %}border-color-gray-400{% endif %}">
            <div class="text-muted"><small>{{ message.date }}</small></div>
            <div class="mt-3">{{ message.body }}</div>
        </div>
        {% if not message.is_from_user %}
            <div class="col-2"></div>
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}

templates/cabinet/chats.html
{% extends 'cabinet/base.html' %}
{% load static %}

{% block subtitle %}
    | Мои сообщения
{% endblock %}

{% block subcontent %}
    <div class="row">
        <div class="col-12 order-2 order-sm-1">
            <div class="d-flex justify-content-end mb-3">
                <a href="{% url 'support:chat' %}" class="btn btn-color-2 css-btn-sm-block">
                    <span class="h6 my-0">Написать сообщение</span>
                </a>
            </div>
        </div>
        <div class="col-12 order-1 order-sm-2">
        {% if not chats %}
            <div class="h5 font-weight-normal text-center">
                Сообщений пока нет
            </div>
            <div class="d-flex justify-content-center mt-3">
                <div class="d-inline-block">
                    <img class="d-block css-width-100px" src="{% static 'img/web_search_125px.png' %}" alt="Ничего не найдено">
                </div>
            </div>
        {% else %}
            <div class="table-responsive-sm">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Тема</th>
                        <th scope="col">Последняя активность</th>
                        <th scope="col">Статус</th>
                    </tr>
                </thead>
                <tbody>
                    {% for chat in chats %}
                    <tr>
                        <th scope="row"><a href="{% url 'profile:chat' chat_slug=chat.slug %}"><span class="text-nowrap">{{ chat.title }}</span></a></th>
                        <td><span class="text-nowrap">{{ chat.message_set.last.date }}</span></td>
                        <td>{{ chat.get_status_display }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/cabinet/order.html
{% extends 'cabinet/base.html' %}
{% load static %}
{% load math %}

{% block subtitle %}
    | Мои заказы | {{ order.slug }}
{% endblock %}

{% block subcontent %}
    <div class="h4">
        Заказ №{{ order.slug }}
    </div>
    {% with last_order_status=order.orderstatus_set.last %}
    <div class="my-3 font-weight-normal">
        Статус заказа: <span class="font-weight-bold">{% if last_order_status %}{{ last_order_status.get_status_display|lower }}{% else %}Оформлено{% endif %}</span>
    </div>
    {% endwith %}
    <hr>
    <div class="h5 my-3 font-weight-normal">
        Заказанные товары
    </div>
    {% for orderproduct in order.orderproduct_set.all %}
        {% with product=orderproduct.product %}
        <div class="d-flex align-items-center">
            <div class="css-width-80px">
                <img class="d-block w-100" src="{{ product.small_photo.url }}" alt="Product {{ product.slug }}">
            </div>
            <div class="d-flex flex-column ml-3">
                <a href="{{ product.origin.get_absolute_url }}?color={{ product.color }}">
                    <div class="h6 my-0 text-color-2">
                        <u>{{ product.origin.name }}</u>
                    </div>
                </a>
                <div class="h6 my-0 mt-1 font-weight-light">
                    {{ product.get_color_display }}
                </div>
            </div>
            <div class="d-flex flex-column ml-3">
                <div class="h6 my-0 font-weight-light">
                    {{ orderproduct.current_price|multiply:orderproduct.quantity }} тг.
                </div>
                <div class="h6 my-0 mt-1 font-weight-light">
                    {{ orderproduct.quantity }} шт.
                </div>
            </div>
        </div>
        <hr>
        {% endwith %}
    {% endfor %}
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="h5 font-weight-normal">
                Информация о доставке
            </div>
            <table class="table table-sm">
                <tbody>
                    <tr>
                        <th scope="row">Имя</th>
                        <td>{{ order.user.name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Телефон</th>
                        <td>{{ order.phone }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Адрес</th>
                        <td>{{ order.address }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Быстрая доставка</th>
                        <td>{% if order.is_fast_delivery %}Да{% else %}Нет{% endif %}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-12 col-md-6 mt-3 mt-md-0">
{#            <hr class="d-md-none">#}
            <div class="h5 font-weight-normal">
                Информация об оплате
            </div>
            <table class="table table-sm">
                <tbody>
                    <tr>
                        <th scope="row">Сумма к оплате</th>
                        <td>{{ order.total_to_pay }} тг.</td>
                    </tr>
                    <tr>
                        <th scope="row">Способ оплаты</th>
                        <td>{{ order.get_payment_method_display }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-12 col-md-6 mt-3">
{#            <hr>#}
            <div class="h5 font-weight-normal">
                История заказа
            </div>
            <table class="table table-sm">
                <tbody>
                    <tr>
                        <th scope="row">Оформлено</th>
                        <td>{{ order.date_created }}</td>
                    </tr>
                    {% for status in order.orderstatus_set.all %}
                    <tr>
                        <th scope="row">{{ status.get_status_display }}</th>
                        <td>{{ status.date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/cabinet/orders.html
{% extends 'cabinet/base.html' %}
{% load static %}

{% block subtitle %}
    | Мои заказы
{% endblock %}

{% block subcontent %}
    {% if not orders %}
    <div>
        <div class="h5 font-weight-normal text-center">
            Заказов пока нет
        </div>
        <div class="d-flex justify-content-center mt-3">
            <div class="d-inline-block">
                <img class="d-block css-width-100px" src="{% static 'img/web_search_125px.png' %}" alt="Ничего не найдено">
            </div>
        </div>
    </div>
    {% else %}
    <div class="table-responsive-sm">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Номер</th>
                <th scope="col">Дата</th>
                <th scope="col">Статус</th>
                <th scope="col">Сумма</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            {% with last_order_status=order.orderstatus_set.last %}
            <tr>
                <th scope="row"><a href="{% url 'profile:order' order_slug=order.slug %}">{{ order.slug }}</a></th>
                <td><span class="text-nowrap">{{ order.date_created }}</span></td>
                <td>{% if last_order_status %}{{ last_order_status.get_status_display }}{% else %}Оформлено{% endif %}</td>
                <td><span class="text-nowrap">{{ order.total_to_pay }} тг.</span></td>
            </tr>
            {% endwith %}
            {% endfor %}
        </tbody>
    </table>
    </div>
    {% endif %}
{% endblock %}

templates/cabinet/settings.html
{% extends 'cabinet/base.html' %}

{% block subtitle %}
    | Настройки
{% endblock %}

{% block subcontent %}
    <div class="h4">
        Данные
    </div>
    <hr>
    <form method="post">
        {% csrf_token %}

        {% with form=user_change_form %}
            {% with field=form.name text='Ваше имя' %}
                {% include 'accounts/form-group.html' %}
            {% endwith %}

            {% include 'accounts/form-errors.html' %}
        {% endwith %}

        <button type="submit" class="btn css-btn-sm-block btn-light border border-color-gray-500 px-4 py-2">
            <span class="h6 my-0">Сохранить</span>
        </button>
    </form>
    <div class="h4 mt-3">
        Пароль
    </div>
    <hr>
    <div class="my-3">
        <a href="{% url 'accounts:password-change' %}" class="btn css-btn-sm-block btn-light border border-color-gray-500 px-4 py-2">
            <span class="h6 my-0">Изменить пароль</span>
        </a>
    </div>
{% endblock %}