accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('activation/<user_email_b64>/<token>/', views.activate_view, name='activate'),
    path('login/', views.login_view, name='login'),
    path('password/reset/', views.password_reset_view, name='password-reset'),
    path('password/set/<user_email_b64>/<token>/', views.password_set_view, name='password-set'),
    path('password/change/', views.password_change_view, name='password-change'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('home')), name='logout'),
]

api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

shop = [
    path('card-carousel/', views.ShopCardCarouselView.as_view(), name='shop-card-carousel'),
    path('cart-add/', views.CartAddView.as_view(), name='cart-add'),
    path('cart-delete/', views.CartDeleteView.as_view(), name='cart-delete'),
    path('cart-delivery/', views.CartDeliveryView.as_view(), name='cart-delivery')
]

urlpatterns = [
    path('shop/', include(shop)),
]

cabinet/urls.py
from django.urls import path

from . import views


app_name = 'profile'

urlpatterns = [
    path('orders/', views.profile_orders_view, name='orders'),
    path('orders/<slug:order_slug>/', views.profile_order_view, name='order'),
    path('chats/', views.profile_chats_view, name='chats'),
    path('chats/<slug:chat_slug>/', views.profile_chat_view, name='chat'),
    path('settings/', views.profile_settings_view, name='settings'),
]

support/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'support'

urlpatterns = [
    path('', views.support_view, name='support'),
    path('<section_name>/<question_index>/', views.question_view, name='question'),
    path('chat/', views.chat_view, name='chat'),
    path('terms-of-service/',
         TemplateView.as_view(template_name='support/terms-of-service.html'),
         name='terms-of-service'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
{#Global site tag (gtag.js) - Google Analytics#}
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-145082281-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-145082281-1');
</script>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if meta_description %}
        <meta name="description" content="{{ meta_description }}">
    {% else %}
        <meta name="description" content="Интернет-магазин качественных и комфортных кресло-мешков, бинбэгов и пуфиков. Доставка по Казахстану. Оплата банковской картой или наличными курьеру.">
    {% endif %}
    <title>
        {% block pretitle %}{% endblock %}
        Кресло-мешки, пуфики и бинбэги | Казахстанский интернет-магазин | Pufiki.kz
        {% block posttitle %}{% endblock %}
    </title>

    {% if canonical_link %}
        <link rel="canonical" href="{{ canonical_link }}">
    {% endif %}

    {% if not indexed %}
        <meta name="robots" content="noindex">
    {% endif %}

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body class="vh-100 d-flex flex-column bg-light js-body">
    <div class="d-block flex-shrink-0">
        {% include 'header.html' %}

        {% block content %}
        {% endblock %}
    </div>

    {% block filler %}
        <div class="flex-fill container-fluid container-fluid-max-width bg-white"></div>
    {% endblock %}

    <div class="d-block flex-shrink-0">
        {% include 'footer.html' %}
    </div>

    {% block script %}
    {% endblock %}

    <script defer src="{% static 'js/main.js' %}"></script>

    {% block postscript %}
    {% endblock %}
</body>
</html>

templates/breadcrumb.html
<nav aria-label="breadcrumb">
    <ol class="breadcrumb my-0">
        {% for name, link_url in results %}
            <li class="breadcrumb-item{% if forloop.last %} active" aria-current="page{% endif %}">
                {% if not forloop.last %}
                    <a href="{% url link_url %}" class="text-body">
                    <u>
                {% endif %}
                {{ name }}
                {% if not forloop.last %}
                    </u>
                    </a>
                {% endif %}
            </li>
        {% endfor %}
    </ol>
</nav>

templates/collapse.html
<a href="#{{ collapse_id }}" class="text-decoration-none" data-toggle="collapse" role="button" aria-expanded="{{ expanded }}" aria-controls="{{ collapse_id }}">
<div
    class="d-flex justify-content-between align-items-center rounded-top js-icon-parent {{ extra_style }}" {# css-icon-angle-{% if expanded == "true" %}up{% else %}down{% endif %}-parent #}
>
    <div class="d-inline-block">
        <div class="{{ font }}">
            {{ collapse_name }}
        </div>
    </div>
    <div class="d-inline-block">
        <div class="css-icon css-icon-24px css-icon-angle-{% if expanded == "true" %}up{% else %}down{% endif %}"></div>
    </div>
</div>
</a>

templates/error.html
{% extends 'base.html' %}

{% block pretitle %}
    Ошибка {{ status }} |
{% endblock %}

{% block content %}
    <div class="container-fluid container-fluid-max-width bg-white">
        <div class="row">
            <div class="col-12 my-3">
                <div class="h4">
                    Ошибка {{ status }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/footer.html
<footer class="container-fluid container-fluid-max-width">
    <div class="row bg-color-3 pt-4">
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 offset-lg-1 order-1 order-sm-1 order-md-1 mt-4 mb-1">
            <div class="d-inline-block">
                <div class="h5 my-0 text-white">
                    Pufiki.kz
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 offset-lg-1 order-3 order-sm-2 order-md-2 mt-4 mb-1">
            <div class="d-inline-block">
                <div class="h5 my-0 text-white">
                    Популярные вопросы
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4 col-lg-3 offset-lg-1 order-5 order-sm-5 order-md-3 mt-4 mb-1">
            <div class="d-inline-block">
                <div class="h5 my-0 text-white">
                    Контакты
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 offset-lg-1 d-flex flex-row flex-sm-column flex-wrap order-2 order-sm-3 order-md-4">
            <div class="d-inline-block mr-4 my-2">
                <a href="{% url 'home' %}" class="text-white">Главная</a>
            </div>
            <div class="d-inline-block mr-4 my-2">
                <a href="{% url 'shop' %}" class="text-white">Каталог</a>
            </div>
            <div class="d-inline-block mr-4 my-2">
                <a href="{% url 'support:support' %}" class="text-white">Поддержка</a>
            </div>
            <div class="d-inline-block my-2">
                <a href="{% url 'accounts:login' %}" class="text-white text-nowrap">Войти / Регистрация</a>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 offset-lg-1 d-flex flex-row flex-sm-column flex-wrap order-4 order-sm-4 order-md-5">
            <div class="d-inline-block mr-4 my-2">
                <a href="{% url 'support:question' section_name='product' question_index='0' %}" class="text-white">Продукция</a>
            </div>
            <div class="d-inline-block mr-4 my-2">
                <a href="{% url 'support:question' section_name='delivery' question_index='0' %}" class="text-white">Доставка</a>
            </div>
            <div class="d-inline-block mr-4 my-2">
                <a href="{% url 'support:question' section_name='payment' question_index='0' %}" class="text-white">Оплата</a>
            </div>
            <div class="d-inline-block mr-4 my-2">
                <a href="{% url 'support:question' section_name='return' question_index='0' %}" class="text-white">Возврат или замена</a>
            </div>
            <div class="d-inline-block my-2">
                <a href="{% url 'support:support' %}" class="text-white">Задайте Ваш вопрос</a>
            </div>
        </div>
        <address class="col-12 col-sm-6 col-md-4 col-lg-3 offset-lg-1 d-flex flex-column order-6 order-sm-6 order-md-6 mb-3">
            <div class="d-inline-block mt-2">
                <span class="text-white">Эл. почта: <a href="mailto:info@pufiki.kz" class="text-white"><u>info@pufiki.kz</u></a></span>
            </div>
            <div class="d-inline-block mt-1">
                <span class="text-white">Телефон: <a href="tel:+77077807477" class="text-white"><u>+77077807477</u></a></span>
            </div>
            <div class="d-inline-block mt-1">
                <span class="text-white">Пон - Пят: 10:00 - 17:00</span>
            </div>
            <div class="d-inline-block mt-1">
                <a href="{% url 'support:chat' %}" class="text-white"><u>Написать сообщение</u></a>
            </div>
        </address>
        <div class="col-12 col-lg-10 offset-lg-1 mt-4 mt-md-5 order-7">
            <p class="text-sm-center text-white small my-0">
                Доставка по Казахстану в течение 1-2 недель. Мы доставляем заказы в Алматы, Нур-Султан (Астана), Актау, Актобе, Атырау, Аксай, Акколь, Балхаш, Жезказган, Караганда, Кокшетау, Костанай, Кызылорда, Талдыкорган, Тараз, Темиртау, Уральск, Усть-Каменогорск, Павлодар, Петропавловск, Семей, Шымкент, Щучинск, Экибастуз и другие регионы.
            </p>
        </div>
{#        <div class="col-12 col-lg-10 offset-lg-1 mt-3 order-8">#}
{#            <div class="text-center text-white small">#}
{#                <a href="{% url 'support:terms-of-service' %}" class="text-white">Условия пользования</a>#}
{#            </div>#}
{#        </div>#}
        <div class="col-12 col-lg-10 offset-lg-1 my-3 order-8">
            <div class="text-center text-white small">
                &copy; 2019 ИП "KZTECHDEV" (Казахстан)
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}

{% with request_url=request.get_full_path %}
<header class="container-fluid container-fluid-max-width px-0 js-header">
    <div class="d-flex align-items-end px-2 px-sm-3 px-lg-4 py-3 bg-white">

        <div class="d-inline-block d-md-none px-1 px-sm-2 py-1 css-icon-hover css-icon-menu-parent js-header-menu-open-toggler">
            <div class="css-icon css-icon-32px css-icon-menu"></div>
        </div>

{#        <div class="d-inline-block border border-color-1 rounded bg-color-1 ml-2 ml-sm-3 ml-md-0">#}
{#            <a href="{% url 'home' %}" class="text-decoration-none text-white">#}
{#                <div class="h5 my-0 p-2">#}
{#                    Pufiki.kz#}
{#                </div>#}
{#            </a>#}
{#        </div>#}

        <div class="d-inline-block ml-2 ml-sm-3 ml-md-0 my-auto py-2">
            <a href="{% url 'home' %}">
                <div class="css-header-logo"></div>
            </a>
        </div>

{#        <div class="d-inline-block ml-2 ml-sm-3 ml-lg-4">#}
{#            <a href="{% url 'shop' %}" class="text-decoration-none text-color-2">#}
{#                <div class="h5 my-0 px-1 px-sm-2">#}
{#                    Каталог#}
{#                </div>#}
{#            </a>#}
{#        </div>#}

        <div class="d-none d-md-inline-block ml-auto my-auto">
            {% url 'shop' as url_link %}
            <a href="{{ url_link }}" class="text-decoration-none">
                <div class="d-flex align-items-center justify-content-center px-2 py-1 css-icon-shop-parent">
                    <div class="d-md-inline-block h6 my-0 {% if request_url == url_link %}text-color-2{% endif %}">
                        Каталог
                    </div>
                    <div class="d-inline-block ml-1">
                        <div class="css-icon css-icon-32px css-icon-shop {% if request_url == url_link %}css-active{% endif %}"></div>
                    </div>
                </div>
            </a>
        </div>

        <div class="d-inline-block ml-auto ml-md-0 ml-lg-3 my-auto">
            {% url 'cart' as url_link %}
            <a href="{{ url_link }}" class="text-decoration-none">
                <div class="d-flex align-items-center justify-content-center px-0 px-sm-2 py-1 css-icon-shopping-cart-parent css-header-cart-items-count-parent">
                    <div class="d-none d-md-inline-block h6 my-0 {% if request_url == url_link %}text-color-2{% endif %}">
                        Корзина
                    </div>
                    <div class="d-inline-block">
                        <div class="css-icon css-icon-32px css-icon-shopping-cart {% if request_url == url_link %}css-active{% endif %}"></div>
                    </div>
                    <div class="d-inline-block ml-1">
                        <span class="h6 my-0 badge text-white css-header-cart-items-count js-header-cart-items-count {% if request_url == url_link %}css-active{% endif %}">{{ cart_items_count }}</span>
                    </div>
                </div>
            </a>
        </div>

        <div class="d-none d-md-inline-block ml-lg-3 my-auto">
            {% url 'support:support' as url_link %}
            <a href="{{ url_link }}" class="text-decoration-none">
                <div class="d-flex align-items-center justify-content-center px-2 py-1 css-icon-help-parent">
                    <div class="d-inline-block h6 my-0 {% if request_url == url_link %}text-color-2{% endif %}">
                        Поддержка
                    </div>
                    <div class="d-inline-block">
                        <div class="css-icon css-icon-32px css-icon-help {% if request_url == url_link %}css-active{% endif %}"></div>
                    </div>
                </div>
            </a>
        </div>

        <nav class="d-none d-md-inline-block ml-lg-3 my-auto">
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <a href="{% url 'profile:orders' %}" class="text-decoration-none dropdown-toggle" data-toggle="dropdown">
                        <div class="d-flex align-items-center justify-content-center px-2 py-1 css-icon-user-parent">
                            <div class="d-inline-block h6 my-0">
                                Мой аккаунт
                            </div>
                            <div class="d-inline-block">
                                <div class="css-icon css-icon-32px css-icon-user"></div>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'profile:orders' %}">Мои заказы</a>
                        <a class="dropdown-item" href="{% url 'profile:chats' %}">Мои сообщения</a>
                        <a class="dropdown-item" href="{% url 'profile:settings' %}">Мои настройки</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Выйти</a>
                    </div>
                </div>
            {% else %}
                {% url 'accounts:login' as url_link %}
                <a href="{{ url_link }}" class="text-decoration-none">
                    <div class="d-flex align-items-center justify-content-center px-2 py-1 css-icon-user-parent">
                        <div class="d-inline-block h6 my-0 text-nowrap {% if request_url == url_link %}text-color-2{% endif %}">
                            Войти / Регистрация
                        </div>
                        <div class="d-inline-block">
                            <div class="css-icon css-icon-32px css-icon-user {% if request_url == url_link %}css-active{% endif %}"></div>
                        </div>
                    </div>
                </a>
            {% endif %}
        </nav>
    </div>

    <nav class="d-md-none">
        <div class="css-md-overlay js-header-menu">
            <div class="d-flex justify-content-end mr-3 mt-3">
                <div class="d-inline-block px-1 px-sm-2 py-1 css-icon-hover css-icon-cancel-parent js-header-menu-close-toggler">
                    <div class="css-icon css-icon-32px css-icon-cancel"></div>
                </div>
            </div>

            <div class="d-flex flex-column">
                <div>
                    <hr>
                </div>

                <div>
                    {% url 'shop' as url_link %}
                    <a href="{{ url_link }}" class="text-decoration-none">
                        <div class="d-flex align-items-center justify-content-center py-0 css-icon-shop-parent">
                            <div class="d-inline-block h6 my-2 {% if request_url == url_link %}text-color-2{% endif %}">
                                Каталог
                            </div>
                            <div class="d-inline-block ml-1">
                                <div class="css-icon css-icon-32px css-icon-shop {% if request_url == url_link %}css-active{% endif %}"></div>
                            </div>
                        </div>
                    </a>
                </div>

                <div>
                    <hr>
                </div>

                <div>
                    {% url 'support:support' as url_link %}
                    <a href="{{ url_link }}" class="text-decoration-none">
                        <div class="d-flex align-items-center justify-content-center py-0 css-icon-help-parent">
                            <div class="d-inline-block h6 my-2 {% if request_url == url_link %}text-color-2{% endif %}">
                                Поддержка
                            </div>
                            <div class="d-inline-block">
                                <div class="css-icon css-icon-32px css-icon-help {% if request_url == url_link %}css-active{% endif %}"></div>
                            </div>
                        </div>
                    </a>
                </div>

                <div>
                    <hr>
                </div>

                {% if user.is_authenticated %}
                    <div>
                        <a href="{% url 'profile:orders' %}" class="text-decoration-none">
                            <div class="h6 my-0 text-center py-2">
                                Мои заказы
                            </div>
                        </a>
                    </div>
                    <div class="mt-3">
                        <a href="{% url 'profile:chats' %}" class="text-decoration-none">
                            <div class="h6 my-0 text-center py-2">
                                Мои сообщения
                            </div>
                        </a>
                    </div>
                    <div class="mt-3">
                        <a href="{% url 'profile:settings' %}" class="text-decoration-none">
                            <div class="h6 my-0 text-center py-2">
                                Мои настройки
                            </div>
                        </a>
                    </div>
                    <div>
                        <hr>
                    </div>
                    <div>
                        <a href="{% url 'accounts:logout' %}" class="text-decoration-none">
                            <div class="h6 my-0 text-center py-2">
                                Выйти
                            </div>
                        </a>
                    </div>
                {% else %}
                    <div>
                        {% url 'accounts:login' as url_link %}
                        <a href="{{ url_link }}" class="text-decoration-none">
                            <div class="d-flex align-items-center justify-content-center py-0 css-icon-user-parent">
                                <div class="d-inline-block h6 my-2 {% if request_url == url_link %}text-color-2{% endif %}">
                                    Войти / Регистрация
                                </div>
                                <div class="d-inline-block">
                                    <div class="css-icon css-icon-32px css-icon-user {% if request_url == url_link %}css-active{% endif %}"></div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>
</header>
{% endwith %}